### ISSUE TITLE
problem with OCR.py

### ISSUE THREAD

**Issue by lchennebault** [arturaugusto/display_ocr#5]
Hi ! I have a problem with OCR.py (ubuntu) :
```
lorisson@lorisson-MS-7677:/usr/lib/python2.7$ /home/lorisson/Bureau/display_ocr-master/OCR.py
Traceback (most recent call last):
  File "/home/lorisson/Bureau/display_ocr-master/OCR.py", line 104, in <module>
    thresh = ConfigSectionMap("PREPROCESS")['threshold']
  File "/home/lorisson/Bureau/display_ocr-master/OCR.py", line 17, in ConfigSectionMap
    options = Config.options(section)
  File "/usr/lib/python2.7/ConfigParser.py", line 279, in options
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'PREPROCESS'
```

**Comment by arturaugusto** [comment]
Try this:
`cd /home/lorisson/Bureau/display_ocr-master/`
`python2.7 OCR.py`
